-- MySQL Script generated by MySQL Workbench
-- Wed Aug 30 15:20:20 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`proyectos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`proyectos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`proyectos` (
  `id_proyecto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `foto_url` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_proyecto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`equipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`equipos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`equipos` (
  `id_equipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `foto_url` VARCHAR(45) NOT NULL,
  `lider_clave_unica` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_equipo`, `lider_clave_unica`),
  INDEX `fk_equipos_usuarios1_idx` (`lider_clave_unica` ASC),
  CONSTRAINT `fk_equipos_usuarios1`
    FOREIGN KEY (`lider_clave_unica`)
    REFERENCES `mydb`.`usuarios` (`clave_unica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `clave_unica` VARCHAR(45) NOT NULL,
  `foto_url` VARCHAR(255) NULL,
  `proyectos_id_proyecto` INT NULL,
  `equipos_id_equipo` INT NULL,
  `tipo` INT NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`, `proyectos_id_proyecto`, `equipos_id_equipo`),
  UNIQUE INDEX `telefono_UNIQUE` (`telefono` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_usuarios_proyectos_idx` (`proyectos_id_proyecto` ASC),
  INDEX `fk_usuarios_equipos1_idx` (`equipos_id_equipo` ASC),
  UNIQUE INDEX `clave_unica_UNIQUE` (`clave_unica` ASC),
  UNIQUE INDEX `proyectos_id_proyecto_UNIQUE` (`proyectos_id_proyecto` ASC),
  UNIQUE INDEX `equipos_id_equipo_UNIQUE` (`equipos_id_equipo` ASC),
  CONSTRAINT `fk_usuarios_proyectos`
    FOREIGN KEY (`proyectos_id_proyecto`)
    REFERENCES `mydb`.`proyectos` (`id_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_equipos1`
    FOREIGN KEY (`equipos_id_equipo`)
    REFERENCES `mydb`.`equipos` (`id_equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`eventos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`eventos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`eventos` (
  `ideventos` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  `lugar` VARCHAR(255) NOT NULL,
  `foto_url` VARCHAR(255) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ideventos`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



            $table->increments('id');
            $table->string('nombre');
            $table->string('apellido');
            $table->string('telefono')->unique();
            $table->string('email')->unique();
            $table->string('password');
            $table->string('clave_unica');
            $table->string('foto_url');
            $table->integer('tipo');
            $table->text('descripcion');
            $table->integer('equipo_id');